name: Deployment
on:
  push:
    branches:
      - main
env:
  CI: false # TODO: fix linting errors and remove this
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Build page
        run: npm run build
      - name: Upload Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'build'
          target: 'temp'
      - name: Replace New Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: rm -rf ~/frontends/coding-minutes-v2/* && cp -rf ~/temp/build/* ~/frontends/coding-minutes-v2 && rm -rf ~/temp